services:
  mongo-dev:
    image: mongo:latest
    container_name: mongo
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: "usr"
#      MONGO_INITDB_ROOT_PASSWORD: "pw"
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  flask:
    build: ./app
    container_name: flask_app
    command:
      - "flask --app run app.py"
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
      FLASK_DEBUG: 1
#      MONGO_INITDB_ROOT_USERNAME: "usr"
#      MONGO_INITDB_ROOT_PASSWORD: "pw"
#      MONGO_HOST: mongo-dev
    ports:
      - "5000:5000"
    depends_on:
      - mongo-dev


volumes:
  mongo_data:
