services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USR}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PW}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  mongo_express:
    image: mongo-express:latest
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USR}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PW}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USR}:${MONGO_PW}@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb

  flask_app:
    build:
      context: ./flask_app
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://${MONGO_USR}:${MONGO_PW}@mongodb:27017/
    depends_on:
      - mongodb

  streamlit_app:
    build:
      context: ./streamlit_app
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - flask_app
##
  jupyter:
    build:
      context: ./jupyter
    container_name: jupyter_notebook
    ports:
      - "8887:8888"
    volumes:
      - ./jupyter/notebooks:/home/work
    depends_on:
      - mongodb

volumes:
  mongo_data:
    name : ${DATABASE_VOLUME}
    driver: local
    driver_opts:
      type: none
      device: ./data/mongo_data
      o: bind