services:
  pre_hook:
    build:
      context : ./pre-hook_script
    container_name  : data_clean_script
    volumes:
      - data_volumes:/data
    environment:
      - INPUT_FILE=/data/superstorerawdata.csv
      - OUTPUT_FILE=/data/superstorerawdata_cleaned.csv

  my_sql_db:
    image: mysql:latest
    container_name: superstore_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - data_volumes:/var/lib/mysql-files/data
    depends_on:
      - pre_hook
    entrypoint: /bin/sh -c 'while [ ! -f /var/lib/mysql-files/data/superstorerawdata_cleaned.csv ]; do echo "Waiting for data_clean_script to create the file..."; sleep 5; done && docker-entrypoint.sh mysqld'

  jupyter:
    build:
      context: ./jupyter
    container_name: jupyter_notebook
    ports:
      - "8887:8888"
    volumes:
      - ./jupyter/notebooks:/home/work
    environment:
      MYSQL_URI: mysql+pymsql://${MYSQL_USER}:${MYSQL_ROOT_PASSWORD}@localhost/${MYSQL_DATABASE_NAME}
    depends_on:
      - my_sql_db

volumes:
  data_volumes:
    name: ${VOLUME_NAME}
    driver: local
    driver_opts:
      type: none
      device: ./data
      o: bind