services:
  my_sql_db:
    image: mysql:latest
    container_name: superstore_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
    volumes:
      - mysql_data_volumes:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../data/superstorerawdata_corrected.csv:/var/lib/mysql-files/superstorerawdata_corrected.csv

  adminer:
    image: adminer
    container_name: superstore_adminer
    depends_on:
      - my_sql_db
    ports:
      - "8080:8080"

  jupyter:
    build:
      context: ./jupyter
    container_name: jupyter_notebook
    ports:
      - "8887:8888"
    volumes:
      - ./jupyter/notebooks:/home/work
    depends_on:
      - my_sql_db

volumes:
  mysql_data_volumes:
    name: ${VOLUME_NAME}
    driver: local
    driver_opts:
      type: none
      device: ./data/mysql_data
      o: bind